baseURL: https://horizonchaser.github.io/neo
title: 'Horizon Blog NEO'

relativeurls: false
defaultContentLanguage: zh-cn
enableRobotsTXT: true
hasCJKLanguage: true
languageCode: zh-cn
rssFullText: false
# rssLimit: 10

publishDir: docs

theme: hugo-theme-hello-friend
copyright: ''
paginate: 10
enableGitInfo: true

params:
  contentTypeName: posts
  defaultTheme: dark
  showMenuItems: 3
  showReadingTime: false
languages:
  zh-cn:
    title: Horizon Blog Neo
    subtitle: ''
    keyword: ''
    menuMore: 查看更多
    writtenBy: 作者：
    readMore: 阅读更多
    readOtherPosts: 阅读其它文章
    newerPosts: 较新的文章
    olderPosts: 较旧的文章
    dateFormatSingle: 2006-01-02
    dateFormatList: 2006-01-02
    lastModDisplay: 最后修改于：
  
    params:
      logo:
        logoText: Horizon Blog Neo
        logoHomeLink: /

    menu:
      main:
        - identifier: about
          name: 关于
          url: /about/
        - identifier: links
          name: 友链
          url: /links/
        - identifier: RSS
          name: RSS
          url: /index.xml